### ISSUE TITLE
ampersand in value appears as &amp; in typeahead box

### ISSUE THREAD

**Issue by groundwired** [SalesforceFoundation/visualforce-typeahead#3]
1) In the test form Account box, type "Uni"
2) Select "United Oil & Gas" account.

Type ahead box shows:  United Oil &amp; Gas

**Comment by iicray** [comment]
The bug can be solved by doing this:
(1) Go to the **Typeahead.component**
(2) Changing Line # 182 from `{escape: true}` to `{escape: false}`

The escape is used for XML escape, not Javascript escape (ref: http://salesforce.stackexchange.com/questions/25691/the-escape-in-visualforce-javascript-remoting)

**Comment by groundwired** [comment]
Thanks!
