### ISSUE TITLE
onkeyup behavior

### ISSUE THREAD

**Issue by iicray** [SalesforceFoundation/visualforce-typeahead#6]
The current onkeyup behavior is to clear the selection if they clear the box completely.

There's a bug.

Let's see the circumstance:

(1) User enter 'sFo' and the suggestion hints there's an account named 'sForce'.
(2) User click the suggested item and get the Id of the 'sForce'
(3) User just enter one "backspace", and the input value now is 'sForc'.
(4) Now, user hits 'Submit', The id of 'sForce' shows. It should not shows, since there's no such a 'sForc' account.

It should be changed to clear anytime the input is modifed (on every keyup). That is just to remove the if condition in the Line#221,222,224.

**Comment by groundwired** [comment]
Good catch.
