### ISSUE TITLE
error when trying to use in iframe

### ISSUE THREAD

**Issue by sd5000** [SalesforceFoundation/visualforce-typeahead#7]
Hey Evan, trying to use the typeahead component in an iframe (popup window) but I get an alert box that says:
`"Javascript proxies were not generated for controller Typeahead: may not use public remoted methods inside an iframe."`

Any idea on how to solve that?

**Comment by groundwired** [comment]
If you change the controller class and method from public to global (simply replace on lines 2 and 5), I believe it should solve the issue.

I would make this change in the repo except that it is not best practice to make code global unless it needs to be global.

**Comment by sd5000** [comment]
That worked great, thanks!
